server.tomcat.uri-encoding: UTF-8
################# mysql--config #################
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
#spring.datasource.url: jdbc:mysql://59.110.162.83/hotel_admin?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Hongkong
#spring.datasource.username: root
#spring.datasource.password: jiayang

spring.datasource.url: jdbc:mysql://localhost:3307/bysj?characterEncoding=utf-8&serverTimezone=GMT
spring.datasource.username: root
spring.datasource.password: hejiahua



spring.datasource.validationQuery: SELECT 1 FROM DUAL
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.show_sql: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#################redis--config#################
spring.redis.database: 0
spring.redis.host: localhost
spring.redis.password:
spring.redis.port: 6379
spring.redis.timeout: 5000
#################redis--thread--config#################
spring.redis.jedis.pool.max-idle: 60
spring.redis.jedis.pool.min-idle: 20
spring.redis.jedis.pool.max-active: 400
spring.redis.jedis.pool.max-wait: 10000
#################dataSource--config#################
spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.timeBetweenEvictionRunsMillis: 60000
spring.datasource.minEvictableIdleTimeMillis: 300000
spring.datasource.testWhileIdle: true
spring.datasource.testOnBorrow: false
spring.datasource.testOnReturn: false
spring.datasource.filters: stat
#################thymeleaf#######################
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.servlet.content-type: text/html
spring.thymeleaf.cache: false

server.port: 8090
####################nodeManager#########
spring.servlet.multipart.maxFileSize: 100
spring.servlet.multipart.maxRequestSize: 100
####################Rabbit MQ#########
spring.rabbitmq.host: 192.168.0.138
spring.rabbitmq.port: 5672
spring.rabbitmq.username: admin
spring.rabbitmq.password: 123456
spring.rabbitmq.publisher-confirms: true
spring.rabbitmq.publisher-returns: true

spring.rabbitmq.listener.simple.acknowledge-mode: manual
spring.rabbitmq.listener.simple.concurrency: 1
spring.rabbitmq.listener.simple.max-concurrency: 1
spring.rabbitmq..listener.simple.retry.enabled: true